### ISSUE TITLE
`non_svg` option is broken for `uploadFile`

### ISSUE THREAD

**Issue by lakenen** [lakenen/node-box-view#3]
The option is being appended to the form as a boolean value, and the form-data api seems to send these values directly into a Buffer, which expects a string or number.

**Comment by sunil12345** [comment]
HI lakenen

I am struggling for the issue how to pass non_svg attribute to box from apex. I have used in setHeader methods in httpRequest and inother places also butnot able to get the proper response.
Here is the small code snippet
Can you please provide some help.

Thanks

**Comment by lakenen** [comment]
@sunil12345 it looks like your code snipped didn't show up. Could you show me what code you're using?

**Comment by sunil12345** [comment]
//String header = '--'+boundary+'\nContent-Disposition: form-data;
name="file";filename="'+file.name+'";\nContent-Type: multipart/form-data';

        //header = header+'\nnon_svg='+True ;

        String header = '--'+boundary+'\nContent-Disposition: form-data;
name="file";filename="'+file.name+'";\nContent-Type:
application/octet-stream';

        //String header = '--'+boundary+'\nContent-Disposition: form-data;
name="file"; filename="'+file.name+'";\nContent-Type:
multipart/form-data;'+'\nnon-svg='+True;

        String footer = '--'+boundary+'--';

        String headerEncoded =
EncodingUtil.base64Encode(Blob.valueOf(header+'\r\n\r\n'));

        HttpResponse res;

I am not able to pass non-svg true to box correctly please guide me

**Comment by lakenen** [comment]
Are you using node-box-view? You shouldn't have to manually manipulate headers.

For `non_svg`, you can simply do:

```js
var client = require('box-view').createClient(MY_AUTH_TOKEN)
var options = {
  params: { non_svg: true }
}
client.uploadFile(someFile, options, function (response) {
  // ...
})
```

**Comment by sunil12345** [comment]
I am notusing node- box -view. Simple box api

**Comment by lakenen** [comment]
Ah. Please send a support request to api@box.com.

**Comment by sunil12345** [comment]
For reference I have asked question in forum
https://support.box.com/hc/en-us/requests/765117

**Comment by sunil12345** [comment]
Thanks lakenen I will do this in the morning
But really thanks for your response.
